name: CI

on:
  workflow_dispatch:
    inputs: 
      environment:
        required: true
        description: Deployment environment.
        options:
          - Development
          - Staging
          - Production
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [ Release ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7

      - name: Execute unit tests
        run: dotnet test